# Generated by Django 5.0.7 on 2024-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_project_proj_create_alter_project_proj_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_desc',
            field=models.TextField(blank=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_desc',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
    ]
