# Generated by Django 5.0.7 on 2024-08-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_project_proj_desc_alter_tasks_task_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mainsite.project', to_field='proj_name'),
        ),
    ]
