# Generated by Django 5.0.7 on 2024-08-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_project_proj_name_alter_tasks_task_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], default='medium', max_length=20, verbose_name='Приоритет задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Готово')], default='pending', max_length=20, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mainsite.project', to_field='proj_name', verbose_name='Проект'),
        ),
    ]
