# Generated by Django 5.0.7 on 2024-08-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auth_user_tasks_task_end_tasks_implementer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth_user',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_end',
            field=models.DateTimeField(null=True, verbose_name='Выполнить до'),
        ),
    ]
