# Generated by Django 5.0.7 on 2024-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_comments_comment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment_create'], 'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания коментария'),
            preserve_default=False,
        ),
    ]
