# Generated by Django 5.0.7 on 2024-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_create'], 'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_create',
            field=models.DateTimeField(null=True, verbose_name='Дата создания коментария'),
        ),
    ]
