# Generated by Django 5.0.7 on 2024-08-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_alter_comments_options_comments_comment_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
