# Generated by Django 5.0.7 on 2024-08-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('comment_create', models.DateTimeField(null=True, verbose_name='Дата создания коментария')),
                ('comment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_coment', to='mainsite.tasks', verbose_name='Коментарий задачи')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coment', to='mainsite.users', verbose_name='Коментарий пользователя')),
            ],
            options={
                'verbose_name': 'Коментарии',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-comment_create'],
            },
        ),
    ]
