# Generated by Django 5.0.7 on 2024-08-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
    ]
