# Generated by Django 5.0.7 on 2024-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_alter_comments_options_remove_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_create'], 'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания коментария'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Ожидает', 'Ожидает'), ('В процессе', 'В процессе'), ('Готово', 'Готово')], default='pending', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
