# Generated by Django 5.0.7 on 2024-08-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_alter_comments_options_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='mainsite.users', to_field='username', verbose_name='Коментарий пользователя'),
        ),
    ]
