# Generated by Django 5.0.7 on 2024-08-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_comments_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_user',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_coment', to='mainsite.users', to_field='username', verbose_name='Коментарий пользователя'),
        ),
    ]
