# Generated by Django 5.0.7 on 2024-08-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_remove_comments_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
