# Generated by Django 5.0.7 on 2024-08-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0027_tasks_sender_alter_tasks_implementer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_coment', to='mainsite.tasks', verbose_name='Коментарий к задаче'),
        ),
    ]
